Conditionalize the build/install of rm(1) on whether -x works

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -629,6 +629,7 @@ LTLIBOBJS
 LIBOBJS
 INSTALL
 SH
+RM
 EGREP
 GREP
 CPP
@@ -4228,6 +4229,27 @@ done
 
 
 
+
+
+# Look for rm -x support.  Exit status 64 is bad argument, 1 is
+# bad file.  So as long as it is not 64 it should be fine.
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking whether rm -x works" >&5
+$as_echo_n "checking whether rm -x works... " >&6; }
+if ${ac_cv_rm_x_works+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  ac_cv_rm_x_works=no
+		rm -x /nonexistent 2>/dev/null
+		test $? -eq 1 && ac_cv_rm_x_works=yes
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_rm_x_works" >&5
+$as_echo "$ac_cv_rm_x_works" >&6; }
+if test "$ac_cv_rm_x_works" = yes; then
+  RM=
+else
+  # Need bundled
+  RM=rm
+fi
 
 
 ac_fn_c_check_decl "$LINENO" "F_DUPFD_CLOEXEC" "ac_cv_have_decl_F_DUPFD_CLOEXEC" "#include <fcntl.h>
