Add 'make gen-man-wiki' to convert manpages to wiki format, rerun on manpage updates

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -114,3 +114,22 @@ poudriered_CFLAGS=	-DPREFIX=\"$(prefix)\" \
 poudriered_LDADD=	libucl.a \
 			-lsbuf \
 			-lutil
+
+.PHONY:	gen-make-wiki
+gen-man-wiki:
+	@if ! which mandoc 2>&1 >/dev/null; then \
+	  echo "Mandoc required, install textproc/mdocml"; \
+	  exit 1; \
+	fi
+	@for man in $(dist_man_MANS); do \
+	  echo "MANDOC doc/$${man##*/}.wiki"; \
+	  ( \
+	    echo "<nowiki>"; \
+	    (mandoc -Thtml $${man} | awk \
+	    '$$1 == "<body>" { seenbody=1; next; }; \
+	     $$1 == "</body>" { seenbody=0; }; \
+	     seenbody == 1 { print };'\
+	    ); \
+	    echo "</nowiki>"; \
+	  ) > doc/$${man##*/}.wiki; \
+	done
diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -1684,6 +1684,25 @@ src/etc/rc.d/poudriered: src/etc/rc.d/poudriered.in
 	@echo "  SED     " $@;
 	@sed -e 's,/usr/local,$(prefix),g' src/etc/rc.d/poudriered.in > $@
 
+.PHONY:	gen-make-wiki
+gen-man-wiki:
+	@if ! which mandoc 2>&1 >/dev/null; then \
+	  echo "Mandoc required, install textproc/mdocml"; \
+	  exit 1; \
+	fi
+	@for man in $(dist_man_MANS); do \
+	  echo "MANDOC doc/$${man##*/}.wiki"; \
+	  ( \
+	    echo "<nowiki>"; \
+	    (mandoc -Thtml $${man} | awk \
+	    '$$1 == "<body>" { seenbody=1; next; }; \
+	     $$1 == "</body>" { seenbody=0; }; \
+	     seenbody == 1 { print };'\
+	    ); \
+	    echo "</nowiki>"; \
+	  ) > doc/$${man##*/}.wiki; \
+	done
+
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
 .NOEXPORT:
